[package]
name = "mil"
version = "0.1.0"
authors = ["Jay Butera <buterajay@protonmail.com>"]
edition = "2018" 

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.1.2"
hex = "0.4.3"
im = "15.0.0"
anyhow = "1.0.41"
genawaiter = "0.99.1"
ethnum = "1.0.3"
#themelio_stf = { git = "https://github.com/themeliolabs/themelio-core" }
themelio-stf = "0.3"
tmelcrypt = "0.1" 
#themelio_stf = { path = "../themelio-core/libs/themelio_stf" }
#tmelcrypt = { path = "../themelio-core/libs/tmelcrypt" }
primitive-types = { version = "0.9.0", default-features = false }
structopt = { version = "0.3.21", default-features = false }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
