[package]
name = "mil"
version = "0.1.0"
authors = ["Jay Butera <buterajay@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.1.2"
blkstructs = { git = "https://github.com/themeliolabs/themelio-core" }
tmelcrypt = { git = "https://github.com/themeliolabs/themelio-core" }
primitive-types = { version = "0.9.0", default-features = false }
structopt = { version = "0.3", default-features = false }
#nom-trace = "0.2.1"

#[dev-dependencies]
